export const endpoints = {
  signup: '/api/v1/auth/signup',
  login: '/api/v1/auth/login',
  refresh: '/api/v1/auth/refresh',
  logout: '/api/v1/auth/logout',
  me: '/api/v1/me',
  roles: '/api/v1/roles',
  currentBusiness: '/api/v1/businesses/current',
  branches: '/api/v1/branches',
  branch: (branchId: string) => `/api/v1/branches/${branchId}`,
  users: '/api/v1/users',
  user: (userId: string) => `/api/v1/users/${userId}`,
  userRoles: (userId: string) => `/api/v1/users/${userId}/roles`,
  userPlacements: (userId: string) => `/api/v1/users/${userId}/placements`,
  workflows: '/api/v1/workflows',
  workflow: (workflowId: string) => `/api/v1/workflows/${workflowId}`,
  workflowStatuses: (workflowId: string) => `/api/v1/workflows/${workflowId}/statuses`,
  workflowTransitions: (workflowId: string) => `/api/v1/workflows/${workflowId}/transitions`,
  serviceDefinitions: '/api/v1/service-definitions',
  serviceOrders: '/api/v1/service-orders',
  serviceOrdersSummary: '/api/v1/service-orders/summary',
  myServiceOrders: '/api/v1/service-orders/mine',
  serviceOrder: (orderId: string) => `/api/v1/service-orders/${orderId}`,
  serviceOrderAssignments: (orderId: string) => `/api/v1/service-orders/${orderId}/assignments`,
  assignServiceOrder: (orderId: string) => `/api/v1/service-orders/${orderId}/assign`,
  transitionServiceOrder: (orderId: string) => `/api/v1/service-orders/${orderId}/transition`,
  serviceOrderUsage: (orderId: string) => `/api/v1/service-orders/${orderId}/resource-usage`,
  resources: '/api/v1/resources',
  resourceAvailability: (resourceId: string) => `/api/v1/resources/${resourceId}/availability`,
  stockMovements: (resourceId: string) => `/api/v1/resources/${resourceId}/stock-movements`,
  auditEvents: '/api/v1/reports/audit-events',
  operationsSummary: '/api/v1/reports/operations-summary',
  platformBusinesses: '/api/v1/platform/businesses',
  platformBusiness: (businessId: string) => `/api/v1/platform/businesses/${businessId}`,
} as const
