imagePullSecrets:
  - name: ghcr-creds

global:
  imageRegistry: ghcr.io
  imageOwner: prabutama
  imageTag: dev
  imagePullPolicy: Always
  timezone: Asia/Jakarta
  natsURL: nats://nats:4222

postgres:
  storageClassName: local-path
  storageSize: 3Gi
  externalNodePort: 30433
  user: mini_erp
  password: mini_erp
  database: postgres

nats:
  storageClassName: local-path
  storageSize: 1Gi

jwt:
  secret: change-me

apiGateway:
  nodePort: 30080

web:
  enabled: true
  repository: mini-erp-web
  imagePullPolicy: Always
  port: 3000

services:
  apiGateway:
    repository: mini-erp-api-gateway
    port: 8080
  identity:
    repository: mini-erp-identity
    grpcPort: 50051
    database: identity_db
  organization:
    repository: mini-erp-organization
    grpcPort: 50052
    database: organization_db
  operations:
    repository: mini-erp-operations
    grpcPort: 50053
    database: operations_db
    natsEnabled: true
  resource:
    repository: mini-erp-resource
    grpcPort: 50054
    database: resource_db
  reporting:
    repository: mini-erp-reporting
    grpcPort: 50055
    database: reporting_db
    natsEnabled: true

ingress:
  enabled: true
  host: mini-erp.prabutama.my.id
