apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    {{- include "mini-erp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.apiGateway.nodePort }}
  selector:
    app.kubernetes.io/component: api-gateway
---
{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if ne $name "apiGateway" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "mini-erp.labels" $root | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: {{ $svc.grpcPort }}
      targetPort: {{ $svc.grpcPort }}
  selector:
    app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
