/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppServiceOrdersRouteImport } from './routes/app.service-orders'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as PlatformBusinessesRouteImport } from './routes/platform.businesses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceOrdersRoute = AppServiceOrdersRouteImport.update({
  id: '/service-orders',
  path: '/service-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const PlatformBusinessesRoute = PlatformBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/platform/businesses': typeof PlatformBusinessesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/platform/businesses': typeof PlatformBusinessesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/platform/businesses': typeof PlatformBusinessesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/platform'
    | '/signup'
    | '/app/branches'
    | '/app/reports'
    | '/app/resources'
    | '/app/service-orders'
    | '/app/services'
    | '/app/users'
    | '/app/workflows'
    | '/platform/businesses'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/platform'
    | '/signup'
    | '/app/branches'
    | '/app/reports'
    | '/app/resources'
    | '/app/service-orders'
    | '/app/services'
    | '/app/users'
    | '/app/workflows'
    | '/platform/businesses'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/platform'
    | '/signup'
    | '/app/branches'
    | '/app/reports'
    | '/app/resources'
    | '/app/service-orders'
    | '/app/services'
    | '/app/users'
    | '/app/workflows'
    | '/platform/businesses'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service-orders': {
      id: '/app/service-orders'
      path: '/service-orders'
      fullPath: '/app/service-orders'
      preLoaderRoute: typeof AppServiceOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/businesses': {
      id: '/platform/businesses'
      path: '/businesses'
      fullPath: '/platform/businesses'
      preLoaderRoute: typeof PlatformBusinessesRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface AppRouteChildren {
  AppBranchesRoute: typeof AppBranchesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppServiceOrdersRoute: typeof AppServiceOrdersRoute
  AppServicesRoute: typeof AppServicesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBranchesRoute: AppBranchesRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppServiceOrdersRoute: AppServiceOrdersRoute,
  AppServicesRoute: AppServicesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformRouteChildren {
  PlatformBusinessesRoute: typeof PlatformBusinessesRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformBusinessesRoute: PlatformBusinessesRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
